#!/bin/bash

# show instructions
echo -e "\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n."

echo -e "\nMake sure you have followed the pi_config file on the desktop. Once done, press ENTER\n"
read -r placeholder
echo -e "\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n."

echo -e "\nDone\n"
sleep 2
echo -e "\nConfiguring System\n"
sleep 2










# configure bash
echo -e "\nConfiguring bash\n"
sleep 2
sudo echo -e "export PS1='\[$(tput bold)\]\[\033[38;5;6m\][\[$(tput sgr0)\]\[\033[38;5;2m\]\u\[$(tput sgr0)\]\[\033[38;5;6m\]@\[$(tput sgr0)\]\[\033[38;5;2m\]\h\[$(tput sgr0)\] \[$(tput sgr0)\]\[$(tput bold)\]\[\033[38;5;208m\]\W\[$(tput sgr0)\]\[\033[38;5;6m\]]\[$(tput sgr0)\]\[\033[38;5;201m\]\\$\[$(tput sgr0)\] \[$(tput sgr0)\]'" >> /home/pi/.bashrc
sudo echo -e "\n# Enables auto-correct" >> /home/pi/.bashrc
sudo echo -e "shopt -s cdspell" >> /home/pi/.bashrc
sudo echo -e "\n# Enables color" >> /home/pi/.bashrc
sudo echo -e "alias diff='diff --color=auto'" >> /home/pi/.bashrc
sudo echo -e "alias grep='grep --color=auto'" >> /home/pi/.bashrc
sudo echo -e "alias ip='ip -color=auto'" >> /home/pi/.bashrc
sudo echo -e "alias ls='ls --color=auto'" >> /home/pi/.bashrc
sudo echo -e "alias sudo='sudo '" >> /home/pi/.bashrc
sudo echo -e "export LESS_TERMCAP_mb=$'\e[1;32m'" >> /home/pi/.bashrc
sudo echo -e "export LESS_TERMCAP_md=$'\e[1;32m'" >> /home/pi/.bashrc
sudo echo -e "export LESS_TERMCAP_me=$'\e[0m'" >> /home/pi/.bashrc
sudo echo -e "export LESS_TERMCAP_se=$'\e[0m'" >> /home/pi/.bashrc
sudo echo -e "export LESS_TERMCAP_so=$'\e[01;91m'" >> /home/pi/.bashrc
sudo echo -e "export LESS_TERMCAP_ue=$'\e[0m'" >> /home/pi/.bashrc
sudo echo -e "export LESS_TERMCAP_us=$'\e[1;4;34m'" >> /home/pi/.bashrc
sudo echo -e "\n# Rewrap text on window resize" >> /home/pi/.bashrc
sudo echo -e "shopt -s checkwinsize" >> /home/pi/.bashrc
sudo echo -e "\n# apt alias" >> /home/pi/.bashrc
sudo echo -e "alias apt-update='sudo apt update && sudo apt full-upgrade'" >> /home/pi/.bashrc
echo -e "\n# NordVPN aliases" >> /home/pi/.bashrc
echo -e "alias nordvpn-disconnect='sudo nordvpn disconnect && sudo nordvpn set killswitch disabled'" >> /home/pi/.bashrc
echo -e "alias nordvpn-connect='sudo nordvpn connect United_States && sudo nordvpn set killswitch enabled'" >> /home/pi/.bashrc
echo -e "\nDone\n"
sleep 2










# configure packages

# configure flatpak and install flatpaks
echo -e "\nConfiguring flatpak\n"
sleep 2
sudo cp /home/pi/personal/flatpak-update.service /etc/systemd/user
sudo cp /home/pi/personal/flatpak-update.timer /etc/systemd/user
systemctl --user daemon-reload
systemctl --user enable --now flatpak-update.timer
flatpak update
echo -e "\nDone\n"
sleep 2

echo -e "\nInstalling flatpaks\n"
sleep 2
sudo apt purge chromium-browser
flatpak install com.github.Eloston.UngoogledChromium
echo -e "\nDone\n"
sleep 2


# configure nordvpn
echo -e "\nCongfiguring NordVPN\n"
sleep 2
nordvpn set technology NordLynx
nordvpn set firewall enabled
nordvpn set notify enabled
nordvpn set autoconnect enabled United_States
nordvpn connect United_States
nordvpn set killswitch enabled
echo -e "\nDone\n"
sleep 2


# configure dolphin
echo -e "\nCongfiguring Dolphin\n"
sleep 2
sudo cp /home/pi/personal/dolphinui.rc /home/pi/.local/share/kxmlgui5/dolphin
sudo echo -e "[General]\nRememberOpenedTabs=false" >> /home/pi/.config/dolphinrc
sudo echo -e "[Settings]\nHiddenFilesShown=true" >> /home/pi/.local/share/dolphin/view_properties/global/.directory
sudo echo -e "[/home/pi/.local/share/Trash]\nDays=14\nLimitReachedAction=0\nPercent=10\nUseSizeLimit=true\nUseTimeLimit=true" >> /home/pi/.config/ktrashrc
echo -e "\nDone\n"
sleep 2


# configure guake
echo -e "\nConfiguring Guake\n"
sleep 2
dconf load /apps/guake/ < /home/pi/personal/guake
sudo mkdir /home/pi/.config/autostart
sudo cp /usr/share/applications/guake.desktop /home/pi/.config/autostart
echo -e "\nDone\n"
sleep 2


# configure kde plasma
echo -e "\nConfiguring Plasma\n"
sleep 2
cp /home/pi/personal/system_monitor.page /home/pi/Desktop
mkdir Pictures
cp /home/pi/personal/wallpaper.jpg /home/pi/Pictures
cp /home/pi/personal/mimeapps.list /home/pi/.config
cp /home/pi/personal/plasma-org.kde.plasma.desktop-appletsrc /home/pi/.config
sudo echo -e "index hidden folders=true" >> /home/pi/.config/baloofilerc
sudo echo -e "only basic indexing=true" >> /home/pi/.config/baloofilerc
sudo echo -e "[DoNotDisturb]\nWhenScreensMirrored=false" > /home/pi/.config/plasmanotifyrc
sudo sed -i 's/\[General\]/\[General\]\nTerminalApplication=guake\nTerminalService=guake.desktop\nBrowserApplication=com.github.Eloston.UngoogledChromium.desktop/' /home/pi/.config/kdeglobals
sudo sed -i 's/LANG=en_GB.UTF-8/LANG=en_US.UTF-8/' /home/pi/.config/plasma-localerc
echo -e "\nDone\n"
sleep 2










# reboot
echo -e "\nRebooting in 5 seconds\n"
sleep 5
reboot
