#!/bin/bash

# show instructions
echo -e "\nDont press any keys until you open qBittorrent and accept the notice. Once done, press ENTER\n"
read -r placeHolder
echo -e "\nDon't press any keys until you follow these instructions:\n\n\nRight click on the desktop and select \"Enter Edit Mode\"\nAdd Widgets\nGet New Widgets\nDownload New Plasma Widgets\ninstall \"Weather Widget\"\n\n\nOnce done, press ENTER\n"
read -r placeHolder










# import personal files
echo -e "\nImporting personal files\n"
sleep 2
git clone https://github.com/soberhippie3/personal
echo -e "\nDone\n"
sleep 2










# configure packages

# configure flatpak and install packages
echo -e "\nConfiguring flatpak\n"
sleep 2
sudo cp /home/pi/personal/flatpak-update.service /etc/systemd/user
sudo cp /home/pi/personal/flatpak-update.timer /etc/systemd/user
systemctl --user daemon-reload
systemctl --user enable --now flatpak-update.timer
flatpak update
flatpak install com.github.Eloston.UngoogledChromium
echo -e "\nDone\n"
sleep 20


# configure qBittorrent
echo -e "\nConfiguring qBittorrent\n"
sleep 2
sudo cp /home/pi/personal/qBittorrent.conf /home/pi/.config/qBittorrent
echo -e "\nDone\n"
sleep 2


# configure dolphin
echo -e "\nCongfiguring Dolphin\n"
sleep 2
sudo cp /home/pi/personal/dolphinui.rc /home/pi/.local/share/kxmlgui5/dolphin
sudo echo -e "[General]\nRememberOpenedTabs=false" >> /home/pi/.config/dolphinrc
sudo echo -e "[Settings]\nHiddenFilesShown=true" >> /home/pi/.local/share/dolphin/view_properties/global/.directory
sudo echo -e "[/home/pi/.local/share/Trash]\nDays=14\nLimitReachedAction=0\nPercent=10\nUseSizeLimit=true\nUseTimeLimit=true" >> /home/pi/.config/ktrashrc
echo -e "\nDone\n"
sleep 20


# configure guake
echo -e "\nConfiguring Guake\n"
sleep 2
sudo cp /usr/share/applications/guake.desktop /home/pi/.config/autostart
echo -e "\nDone\n"
sleep 2


# configure kde plasma
echo -e "\nConfiguring Plasma\n"
sleep 2
cp /home/pi/personal/guake /home/pi/Desktop
cp /home/pi/personal/system_monitor.page /home/pi/Desktop
cp /home/pi/personal/wallpaper.jpg /home/pi/Pictures
cp /home/pi/personal/mimeapps.list /home/pi/.config
cp /home/pi/personal/plasma-org.kde.plasma.desktop-appletsrc /home/pi/.config
sudo echo -e "index hidden folders=true" >> /home/pi/.config/baloofilerc
sudo echo -e "only basic indexing=true" >> /home/pi/.config/baloofilerc
sudo echo -e "[DoNotDisturb]\nWhenScreensMirrored=false" > /home/pi/.config/plasmanotifyrc
sudo sed -i 's/\[General\]/\[General\]\nTerminalApplication=guake\nTerminalService=guake.desktop\nBrowserApplication=com.github.Eloston.UngoogledChromium.desktop/' /home/pi/.config/kdeglobals
echo -e "\nDone\n"
sleep 2










# reboot
echo -e "\nRebooting in 5 seconds\n"
sleep 5
reboot
