#!/bin/bash





# install kde plasma
echo -e "\nInstalling KDE Plasma\n"
sleep 2
sudo apt install flatpak kde-standard sddm xorg
# sudo systemctl enable sddm
sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
echo -e "\nDone\n"
sleep 2





# import personal files
echo -e "\nImporting personal files\n"
sleep 2
git clone https://github.com/ksanf3/personal
mkdir /home/pi/Desktop
cp /home/pi/personal/1-pi-packages /home/pi/Desktop
cp /home/pi/personal/2-pi-config /home/pi/Desktop
echo -e "\nDone\n"
sleep 2










# show final instructions
echo -e "\n\n\n\n\n\n\n\n\n\nFinal Instructions\n"
echo -e "\nrun the command \"sudo raspi-config\"\n"
echo -e "\nenable boot to desktop through \"System Options\"\n"
reboot
