#!/bin/bash
# this script will configure the system and install KDE Plasma










# install packages
echo -e "\nInstalling necessary packages\n"
sleep 2
apt install kde-plasma-desktop guake flatpak vlc
echo -e "\nDone\n"
sleep 2


# configure packages
echo -e "\nConfiguring packages\n"
sleep 2
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
echo -e "\nDone\n"
sleep 2
